#!/usr/bin/env python3
"""AeroThermalStudio entry point.

Launches either the desktop GUI or the MCP server from one command, so the
same installation serves a human operator and an AI agent:

    python run_app.py --gui      # desktop application
    python run_app.py --mcp      # MCP server on stdio
    python run_app.py --check    # report the detected toolchain
    python run_app.py --demo     # build sample CAD and mesh it

Both surfaces read the same parameter core and the same run registry, so a
mesh generated by an agent opens in the GUI and vice versa.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Make the package importable when run from any directory.
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def launch_gui(argv: list[str] | None = None) -> int:
    """Start the PySide6 desktop application."""
    try:
        from gui.main_window import run_gui
    except ImportError as error:
        print(
            "The GUI needs PySide6 and pyvistaqt:\n"
            "    pip install PySide6 pyvistaqt\n"
            f"(import failed: {error})",
            file=sys.stderr,
        )
        return 2
    return run_gui(argv or [])


def launch_mcp() -> int:
    """Start the MCP server on stdio."""
    try:
        from mcp_server import main as mcp_main
    except ImportError as error:
        print(
            "The MCP server needs the Model Context Protocol SDK:\n"
            "    pip install mcp\n"
            f"(import failed: {error})",
            file=sys.stderr,
        )
        return 2
    mcp_main()
    return 0


def report_environment(as_json: bool = False) -> int:
    """Print the detected solver toolchain."""
    from core.platform_env import probe_environment

    report = probe_environment(probe_versions=True)
    if as_json:
        print(json.dumps(report.as_dict(), indent=2))
        return 0 if report.solver_ready else 1

    print("AeroThermalStudio environment")
    print("-" * 46)
    print(f"  Operating system : {report.os_name}")
    print(f"  Python           : {report.python_version}")
    print(f"  Logical CPUs     : {report.cpu_count}")
    print(f"  Suggested ranks  : {report.recommended_ranks}")
    print(f"  Data directory   : {report.data_root}")
    print(f"  MPI launcher     : {report.mpi_launcher or 'NOT FOUND'}")
    print(f"  SU2_CFD          : {report.su2_cfd or 'NOT FOUND'}")
    if report.su2_version:
        print(f"  SU2 version      : {report.su2_version}")

    if report.solver_ready:
        print("\n  Solver stack ready.")
        return 0

    print("\n  Missing components:")
    for item in report.missing:
        print(f"    - {item}")
    print("\n  Run 'python setup_env.py' to install them.")
    return 1


def run_demo(output_directory: Path | None = None) -> int:
    """Build the sample rocket and mesh it, as a first-run smoke test.

    Exercises CAD generation, alignment, prism extrusion and SU2 export
    without needing the solver installed.
    """
    from backend.mesh_pipeline import generate_mesh
    from backend.sample_geometry import create_reference_rocket_step
    from core.models import (
        FlowParams,
        GeometryParams,
        MeshParams,
        MeshRequest,
        MeshResolution,
        SimulationTrack,
    )
    from core.store import default_store

    store = default_store()
    record = store.create("mesh", {"source": "demo"})
    directory = Path(output_directory) if output_directory else record.directory

    print("Building the reference rocket CAD ...")
    step_path = create_reference_rocket_step(directory / "reference_rocket.step")
    print(f"  wrote {step_path}")

    request = MeshRequest(
        geometry=GeometryParams(step_file_path=str(step_path)),
        mesh=MeshParams(
            track=SimulationTrack.AERODYNAMIC,
            resolution=MeshResolution.COARSE,
            boundary_layers=6,
            max_targeting_iterations=2,
        ),
        sizing_flow=FlowParams(velocity_value=2.0),
    )

    print("Meshing (this takes a minute) ...")
    result = generate_mesh(
        request, directory / "mesh.su2", progress=lambda m: print(f"  {m}")
    )

    print("\nMesh report")
    print("-" * 46)
    print(f"  Cells            : {result.cell_count:,}")
    print(f"  Nodes            : {result.node_count:,}")
    print(f"  Target band      : {result.target_band[0]:,} - {result.target_band[1]:,}")
    print(f"  Within band      : {result.within_target_band}")
    print(f"  Reference length : {result.reference_length_m:.4f} m")
    print(f"  Reference diam.  : {result.reference_diameter_m:.4f} m")
    print(f"  Achieved y+      : {result.estimated_yplus:.1f}")
    print(f"  Minimum quality  : {result.min_quality:.3f}")
    print(f"  Markers          : {result.boundary_markers}")
    print(f"  Mesh file        : {result.mesh_path}")

    store.update_metadata(
        record.record_id,
        {
            "mesh_path": result.mesh_path,
            "cell_count": result.cell_count,
            "reference_area_m2": result.reference_area_m2,
            "reference_length_m": result.reference_length_m,
        },
    )
    print(f"\n  Stored as mesh_id: {record.record_id}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    """Command-line interface."""
    parser = argparse.ArgumentParser(
        prog="run_app.py",
        description=(
            "AeroThermalStudio - rocket aerodynamics and sensor microclimate CFD"
        ),
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--gui", action="store_true", help="launch the desktop application"
    )
    mode.add_argument(
        "--mcp", action="store_true", help="run the MCP server on stdio"
    )
    mode.add_argument(
        "--check", action="store_true", help="report the detected toolchain"
    )
    mode.add_argument(
        "--demo",
        action="store_true",
        help="build the sample rocket and mesh it as a smoke test",
    )
    parser.add_argument(
        "--json", action="store_true", help="machine-readable output for --check"
    )
    parser.add_argument(
        "--output", type=Path, default=None, help="output directory for --demo"
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """Dispatch to the requested mode, defaulting to the GUI."""
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.mcp:
        return launch_mcp()
    if args.check:
        return report_environment(as_json=args.json)
    if args.demo:
        return run_demo(args.output)
    if args.gui:
        return launch_gui()

    # No mode given: show the environment and the available modes.
    parser.print_help()
    print()
    return report_environment(as_json=args.json)


if __name__ == "__main__":  # pragma: no cover - entry point
    raise SystemExit(main())
