"""Filesystem-backed registry of meshes and simulation runs.

Both the GUI and the MCP server address artefacts by ``mesh_id`` / ``sim_id``,
so a mesh generated by an AI agent can be visualised from the GUI and vice
versa. Each record is a directory holding the parameters it was created from,
the solver inputs, and whatever outputs the stage produced.
"""

from __future__ import annotations

import json
import shutil
import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator, Literal

from pydantic import BaseModel

from core.platform_env import data_root

RecordKind = Literal["mesh", "aero", "thermal", "sweep", "shield"]

_METADATA_FILENAME = "record.json"
# A record id anywhere in text. Older ids end in six random hex digits;
# current ones have no tail, or -2, -3 ... when two share a second.
RUN_ID_PATTERN = r"(?:mesh|aero|therm|sweep|shield)-\d{8}-\d{6}(?:-[0-9a-f]{6}|-\d{1,2})?"

_ID_PREFIXES: dict[RecordKind, str] = {
    "mesh": "mesh",
    "aero": "aero",
    "thermal": "therm",
    "sweep": "sweep",
    "shield": "shield",
}


def _utc_now_iso() -> str:
    """Current UTC timestamp in ISO-8601 form."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _json_default(value: Any) -> Any:
    """JSON encoder fallback handling Pydantic models, paths and enums."""
    if isinstance(value, BaseModel):
        return value.model_dump(mode="json")
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, set):
        return sorted(value)
    raise TypeError(f"object of type {type(value).__name__} is not JSON serialisable")


@dataclass(frozen=True)
class RunRecord:
    """A single stored mesh or simulation."""

    record_id: str
    kind: RecordKind
    directory: Path
    created_at: str
    metadata: dict[str, Any]

    def path(self, *parts: str) -> Path:
        """Build a path inside this record's directory."""
        return self.directory.joinpath(*parts)

    def exists(self, *parts: str) -> bool:
        """True when the given relative path exists inside the record."""
        return self.path(*parts).exists()

    def as_dict(self) -> dict[str, Any]:
        """Return the record as a JSON-serialisable dictionary."""
        return {
            "record_id": self.record_id,
            "kind": self.kind,
            "directory": str(self.directory),
            "created_at": self.created_at,
            "metadata": self.metadata,
        }


class RecordNotFoundError(KeyError):
    """Raised when a mesh_id or sim_id does not resolve to a stored record."""


class RunStore:
    """Registry of run directories rooted at the application data directory.

    Parameters
    ----------
    root:
        Base directory. Defaults to the platform data root, which the
        ``ATS_DATA_ROOT`` environment variable can override for tests.
    """

    def __init__(self, root: Path | str | None = None) -> None:
        self._root = Path(root).expanduser().resolve() if root else data_root()
        self._runs_dir = self._root / "runs"
        self._runs_dir.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()

    @property
    def root(self) -> Path:
        """Base data directory."""
        return self._root

    @property
    def runs_dir(self) -> Path:
        """Directory containing one subdirectory per record."""
        return self._runs_dir

    def new_id(self, kind: RecordKind) -> str:
        """A readable identifier: the kind and the local time it was made.

        ``aero-20260924-143012`` reads as the clock on the operator's wall,
        not UTC, and carries no random tail. Two records in the same second
        get ``-2``, ``-3`` and so on.
        """
        prefix = _ID_PREFIXES[kind]
        base = f"{prefix}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        identifier = base
        counter = 2
        while (self._runs_dir / identifier).exists():
            identifier = f"{base}-{counter}"
            counter += 1
        return identifier

    def create(
        self,
        kind: RecordKind,
        metadata: dict[str, Any] | None = None,
        record_id: str | None = None,
    ) -> RunRecord:
        """Create a new record directory and write its metadata."""
        with self._lock:
            identifier = record_id or self.new_id(kind)
            directory = self._runs_dir / identifier
            if directory.exists():
                raise FileExistsError(f"record '{identifier}' already exists")
            directory.mkdir(parents=True)
            record = RunRecord(
                record_id=identifier,
                kind=kind,
                directory=directory,
                created_at=_utc_now_iso(),
                metadata=dict(metadata or {}),
            )
            self._write_metadata(record)
            return record

    def _write_metadata(self, record: RunRecord) -> None:
        """Persist a record's metadata atomically."""
        payload = {
            "record_id": record.record_id,
            "kind": record.kind,
            "created_at": record.created_at,
            "metadata": record.metadata,
        }
        target = record.directory / _METADATA_FILENAME
        temporary = target.with_suffix(".json.tmp")
        temporary.write_text(
            json.dumps(payload, indent=2, default=_json_default), encoding="utf-8"
        )
        temporary.replace(target)

    def get(self, record_id: str) -> RunRecord:
        """Load a record by identifier.

        Raises
        ------
        RecordNotFoundError
            If no such record directory exists.
        """
        directory = self._runs_dir / record_id
        metadata_path = directory / _METADATA_FILENAME
        if not metadata_path.is_file():
            raise RecordNotFoundError(
                f"no record '{record_id}' under {self._runs_dir}"
            )
        payload = json.loads(metadata_path.read_text(encoding="utf-8"))
        return RunRecord(
            record_id=payload["record_id"],
            kind=payload["kind"],
            directory=directory,
            created_at=payload["created_at"],
            metadata=payload.get("metadata", {}),
        )

    def update_metadata(self, record_id: str, updates: dict[str, Any]) -> RunRecord:
        """Merge new keys into a record's metadata and persist it."""
        with self._lock:
            record = self.get(record_id)
            merged = {**record.metadata, **updates}
            updated = RunRecord(
                record_id=record.record_id,
                kind=record.kind,
                directory=record.directory,
                created_at=record.created_at,
                metadata=merged,
            )
            self._write_metadata(updated)
            return updated

    def write_json(self, record_id: str, filename: str, payload: Any) -> Path:
        """Write a JSON document (or Pydantic model) inside a record."""
        record = self.get(record_id)
        target = record.path(filename)
        target.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(payload, BaseModel):
            text = payload.model_dump_json(indent=2)
        else:
            text = json.dumps(payload, indent=2, default=_json_default)
        target.write_text(text, encoding="utf-8")
        return target

    def read_json(self, record_id: str, filename: str) -> Any:
        """Read a JSON document stored inside a record."""
        record = self.get(record_id)
        target = record.path(filename)
        if not target.is_file():
            raise RecordNotFoundError(
                f"record '{record_id}' has no file '{filename}'"
            )
        return json.loads(target.read_text(encoding="utf-8"))

    def list_records(self, kind: RecordKind | None = None) -> list[RunRecord]:
        """All stored records, newest first, optionally filtered by kind."""
        records: list[RunRecord] = []
        for directory in self._runs_dir.iterdir():
            if not (directory / _METADATA_FILENAME).is_file():
                continue
            try:
                record = self.get(directory.name)
            except (RecordNotFoundError, json.JSONDecodeError):
                continue
            if kind is None or record.kind == kind:
                records.append(record)
        return sorted(records, key=lambda r: r.created_at, reverse=True)

    def iter_records(self, kind: RecordKind | None = None) -> Iterator[RunRecord]:
        """Iterate over stored records, newest first."""
        yield from self.list_records(kind)

    def delete(self, record_id: str) -> None:
        """Remove a record directory and everything inside it."""
        with self._lock:
            record = self.get(record_id)
            shutil.rmtree(record.directory)

    def resolve_mesh_path(self, mesh_id: str) -> Path:
        """Return the ``.su2`` mesh file path for a stored mesh record.

        Raises
        ------
        RecordNotFoundError
            If the record is missing, is not a mesh, or has no mesh file.
        """
        record = self.get(mesh_id)
        if record.kind != "mesh":
            raise RecordNotFoundError(
                f"record '{mesh_id}' is a '{record.kind}' record, not a mesh"
            )
        stored = record.metadata.get("mesh_path")
        candidate = Path(stored) if stored else record.path("mesh.su2")
        if not candidate.is_file():
            raise RecordNotFoundError(
                f"mesh record '{mesh_id}' has no mesh file at {candidate}"
            )
        return candidate


_default_store: RunStore | None = None
_default_store_lock = threading.Lock()


def default_store() -> RunStore:
    """Process-wide :class:`RunStore` shared by the GUI and MCP server."""
    global _default_store
    with _default_store_lock:
        if _default_store is None:
            _default_store = RunStore()
        return _default_store


def reset_default_store() -> None:
    """Drop the cached default store (used by tests after changing the root)."""
    global _default_store
    with _default_store_lock:
        _default_store = None
